---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: default
  labels:
{{ include "nginx.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: {{ .Values.ports.name }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: NodePort
  selector:
    app: {{ .Chart.Name | quote }}
...
