---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.global.volumeMounts.mountPath | quote }}
...
