---
- name: Rebuild Satis with updated assets
  hosts: darwin
  connection: local
  vars_files: defaults/main.yaml
  gather_facts: false
  tasks:
    - name: Get the Satis pod generated label
      tags: query
      block:
        - name: Query for the Satis pod name
          ansible.builtin.command: kubectl get pods -l app=satis-php --no-headers=true -o name
          register: podname
          changed_when: podname.rc != 0

        - name: Trim the pod/ prefix from the variable value
          ansible.builtin.set_fact:
            podname: "{{ podname.stdout | regex_replace('pod/', '', count=1) }}"

    - name: Transfer the miscellaneous assets to the Satis pod
      tags: assets
      block:
        - name: Copy the auth.json
          ansible.builtin.command: kubectl cp assets/auth.json {{ NAMESPACE }}/{{ podname }}:{{ INSTALL }}

        - name: Capture the value of the Node port
          ansible.builtin.command: minikube service satis-nginx --url
          register: nodeport
          changed_when: nodeport.rc != 0

        - name: Replace the homepage placeholder with the actual url
          ansible.builtin.lineinfile:
            path: 'assets/satis.json'
            search_string: '"homepage": "",'
            line: '    "homepage": "{{ nodeport.stdout }}",'
            mode: '0644'

        - name: Replace the prefix-url placeholder with the actual url
          ansible.builtin.lineinfile:
            path: 'assets/satis.json'
            search_string: '"prefix-url": "",'
            line: '        "prefix-url": "{{ nodeport.stdout }}",'
            mode: '0644'

        - name: Copy the satis.json
          ansible.builtin.command: kubectl cp assets/satis.json {{ NAMESPACE }}/{{ podname }}:{{ INSTALL }}

    - name: Rebuild the Satis repository
      tags: jobs
      block:
        - name: Delete the existing job
          ansible.builtin.command: kubectl delete job satis-rebuild --ignore-not-found

        - name: Run the new job
          ansible.builtin.command: kubectl apply -f rebuild.yaml
...
