---
apiVersion: v2
name: satis-nginx
description: Deploy an NGiNX proxy for Satis
icon: https://github.com/farghul/satis/blob/main/icons/helm.svg
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"

dependencies:
- name: satis-php
  version: "~0.0.1"
  repository: "file://charts/php"
...
