---
name: Satis CI

on:
  push:
    branches:
      - main
    paths:
      - "docker/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: satis-build
  cancel-in-progress: true

jobs:
  build:
    name: Build Satis Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Build and Push
        uses: docker/bake-action@v7
        with:
          files: docker/docker-bake.hcl
          push: true

      - name: Login to OCP SILVER
        uses: docker/login-action@v4
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: serviceaccount
          password: ${{ secrets.C329BD_TOOLS_SA_GHA_TOKEN }}

      - name: Tag and Push Docker image
        run: |
          docker image tag nginx:latest image-registry.apps.silver.devops.gov.bc.ca/${{ vars.OCP_LICENSE_PLATE }}-tools/nginx-satis:latest
          docker image tag php:latest image-registry.apps.silver.devops.gov.bc.ca/${{ vars.OCP_LICENSE_PLATE }}-tools/php-satis:latest
          docker push image-registry.apps.silver.devops.gov.bc.ca/${{ vars.OCP_LICENSE_PLATE }}-tools/nginx-satis:latest
          docker push image-registry.apps.silver.devops.gov.bc.ca/${{ vars.OCP_LICENSE_PLATE }}-tools/php-satis:latest
...
